winzou_state_machine:
    sylius_payment:
        callbacks:
            before:
                payplug_sylius_payplug_plugin_refund_process:
                    on: ["refund"]
                    do: ["@payplug_sylius_payplug_plugin.payment_processing.refund", "process"]
                    args: ["object"]
                payplug_sylius_payplug_plugin_failed_process:
                    on: ["fail"]
                    do: ["@payplug_sylius_payplug_plugin.payment_processing.abort", "process"]
                    args: ["object"]
                payplug_sylius_payplug_plugin_complete:
                    on: ["complete"]
                    do: ["@payplug_sylius_payplug_plugin.payment_processing.capture", "process"]
                    args: ["object"]
