name: CI

'on':
    pull_request:
        branches:
            - develop
            - master
        paths-ignore:
            - README.md

jobs:
    quality:
        uses: payplug/template-ci/.github/workflows/sylius_quality.yml@main

    sylius-matrix:
        needs: [quality]
        if: github.base_ref == 'develop'
        uses: payplug/template-ci/.github/workflows/sylius_phpunit.yml@main

    sonarcloud:
        if: always() && !failure() && !cancelled() && github.base_ref == 'develop'
        needs: sylius-matrix
        uses: payplug/template-ci/.github/workflows/sonarcloud.yml@main
        with:
            project-name: 'github-payplug-payplug-syliuspayplugplugin'
            src-folder: 'src/'
        secrets:
            sonar-orga: ${{ secrets.SONAR_ORGA }}
            sonar-token: ${{ secrets.SONAR_TOKEN }}
