name: CREATE JIRA ISSUE

on:
  issues:
    types: [opened, edited]

jobs:
  jira:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        env:
          TITLE_ISSUE: ${{ github.event.issue.title }}
          BODY_ISSUE: | 
            ${{ github.event.issue.body }}
        with:
          project: SMP
          issuetype: Sylius Technical Support
          summary: "${{ env.TITLE_ISSUE }}  #${{ github.event.issue.number }}"
          # Valeur par default "from github" en MVP
          fields: >
            {
              "customfield_10150": "${{ env.BODY_ISSUE | replace('\\n', '\\r') | replace('\\r\\r', '\\r') | replace('\"', '\\\"') }}",
              "customfield_10106": "from github",
              "customfield_10105": "https://www.from-github.fr",
              "customfield_10108": "from github",
              "customfield_10145": "from github"
            }
      
      - name: Log
        run: echo "Created issue ${{ steps.create.outputs.issue }}"
