name: CREATE JIRA ISSUE

on:
  issues:
    types: [opened, edited]

jobs:
  jira:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: SMP
          issuetype: Sylius Technical Support
          summary: "${{ github.event.issue.title }} #${{ github.event.issue.number }}"
          # Valeur par default "from github" en MVP
          fields: '{"customfield_10150": "${{ github.event.issue.body }}\n\nCreated from GitHub Action", "customfield_10106": "from github","customfield_10105": "https://www.from-github.fr","customfield_10108": "from github", "customfield_10145": "from github"}'

      - name: Log
        run: echo "Created issue ${{ steps.create.outputs.issue }}"
